### ISSUE TITLE
mongodb fooditem

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#95]
- [x] FoodItem
  ![bildschirmfoto 2017-10-08 um 10 41 39](https://user-images.githubusercontent.com/6609359/31315292-a8e0b0fc-ac15-11e7-80f7-fb9ca940bef4.png)
- [x] extend Fooditem Template with Unit Ref Id and Category Ref Ids
- [ ] testing
- [x] readme

**Comment by hetec** [comment]
yes I'm with you. The recipe ingredients had a similar error. I have put a ingredients array on the recipe instead of adding a recipe ref to the ingredient.

I currently ask myself why the categories and unit sits on the food item and not the template?! Aren't the part of the template? Example:

We have a apple template (food item of type apple 🍎 )
=> apple, cat: fruit, unit: piece, ...

And the we have multiple instances of the apple template (the concrete apples in our fridge)
=> These apples have a specific best before date and can be used for cooking (the amount will be decreased if you cook sth. with apples)

?!
